/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Requirements',
      items: [{type: 'autogenerated', dirName: 'catalog/requirements'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'catalog/architecture'}],
    },
    {
      type: 'category',
      label: 'Development',
      items: [{type: 'autogenerated', dirName: 'catalog/development'}],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{type: 'autogenerated', dirName: 'catalog/operations'}],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [{type: 'autogenerated', dirName: 'catalog/testing'}],
    },
    {
      type: 'category',
      label: 'Decommission',
      items: [{type: 'autogenerated', dirName: 'catalog/decommission'}],
    },
    {
      type: 'category',
      label: 'End User',
      items: [{type: 'autogenerated', dirName: 'catalog/end-user'}],
    },
  ],
};

module.exports = sidebars;
